/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppLoading: typeof import('./src/components/AppLoading.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Popup: typeof import('./src/components/Popup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskItem: typeof import('./src/components/TaskItem.vue')['default']
    TaskList: typeof import('./src/components/TaskList.vue')['default']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
  }
}
